### ISSUE TITLE
 ModuleNotFoundError: No module named 'vlocnext' when running train.py

### ISSUE THREAD

**Issue by frozencoolcool** [TruongKhang/DeViLoc#2]
I encountered a `ModuleNotFoundError: No module named 'vlocnext'` error when running `train.py` using Python. Could you please provide some guidance on how to resolve this issue? I would greatly appreciate any help or suggestions you can offer.

Thank you in advance for your assistance!

**Comment by TruongKhang** [comment]
hi @frozencoolcool , this happens when I refactor the code (I changed the name of main module `vlocnext` --> `deviloc`)
I'll resolve this issue and let you know soon!

**Comment by TruongKhang** [comment]
Hi @frozencoolcool, I fixed and updated the code.
Feel free to ask if you have any problems!
